on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  ci:
    strategy:
      matrix:
        jvm:
          - temurin:1.8.0-422
          - temurin:1.21
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: ${{ matrix.jvm }}
          apps: sbt
      - name: Run tests
        run: sbt +test
